meta_product_name: "Obras y Contratas Patrimonial"
meta_title: "Obras y Contratas Patrimonial - Reformas y construcción en Barcelona"
meta_description: "Empresa de reformas y construcción en Barcelona. Trabajos de lampistería, albañilería, trabajos verticales, reformas integrales, asesoramiento inmobiliario, promoción de construcción. Somos instaladores oficiales certificados."
meta_image: "patrimonial.png" # should exist in `app/assets/images/`
